import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { FC, PropsWithChildren } from "react";
import { Toaster } from "sonner";
import MuiProvider from "@/config/MuiProvider";
import ReactQueryProvider from "@/config/ReactQueryProvider";
import "./globals.css";
import I18nProvider from "@/config/I18nProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = PropsWithChildren;

const RootLayout: FC<Props> = ({ children }) => {
  return (
    <html lang="es">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <I18nProvider>
          <ReactQueryProvider>
            <MuiProvider>
              <Toaster position="bottom-right" richColors closeButton />
              {children}
            </MuiProvider>
          </ReactQueryProvider>
        </I18nProvider>
      </body>
    </html>
  );
};

export default RootLayout;
